services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: taxilf-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxilfDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taxilf-network

  redis:
    image: redis:7.4.0-alpine
    container_name: taxilf-redis
    ports:
      - "6379:6379"
    networks:
      - taxilf-network

volumes:
  postgres_data:

networks:
  taxilf-network:
